# -*- coding: utf-8 -*-
"""Tensorflow_Classificator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXm7EGL6-N--T5d9p9MZ-Vbhbpaej0Bw
"""

import tensorflow as tf 
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

(imagens_treinamento, labels_treinamento),(imagens_teste, labels_teste) = datasets.cifar10.load_data()
imagens_teste = imagens_teste/255
imagens_treinamento = imagens_treinamento/255

nome_classes = ['avião', 'automovel', 'passaro', 'gato', 'cervo', 'cachorro', 'sapo', 'cavalo', 'navio', 'caminhão']
plt.figure(figsize=(15,15))
for i in range(25):
   plt.subplot(5,5,i+1)
   plt.grid(False)
   plt.xticks([])
   plt.yticks([])
   plt.imshow(imagens_treinamento[i])
   plt.xlabel(nome_classes[labels_treinamento[i][0]])
plt.show()

cnn = models.Sequential()
cnn.add(layers.Conv2D(32,(3,3), activation= 'relu', input_shape = (32,32,3)))
cnn.add(layers.MaxPool2D((2,2)))
cnn.add(layers.Conv2D(64,(3,3), activation= 'relu'))
cnn.add(layers.MaxPool2D((2,2)))
cnn.add(layers.Conv2D(64,(3,3), activation= 'relu'))
cnn.add(layers.Flatten())
cnn.add(layers.Dense(128, activation= 'relu'))
cnn.add(layers.Dense(10))

cnn.summary()

cnn.compile(optimizer= 'Adam', loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
historia = cnn.fit(imagens_treinamento, labels_treinamento, epochs= 10, validation_data=(imagens_teste, labels_teste))